import type { Metadata } from "next";
import { Footer, Header } from "../site-shell";
import { sitePath } from "../site-path";
import { WhyDifferent } from "../why-different";

export const metadata: Metadata = { title:"About", description:"Meet the multidisciplinary team building NeuroVision." };

const team = [
  { name:"Patrik Molnar", role:"CEO & Chief Scientist", founder:true, image:sitePath("/assets/team-patrik.webp"), bio:"Patrik is a computational neuroscience researcher exploring how neuroscience and biophysics can inspire the next generation of intelligent systems. He currently works at the Chinese Academy of Sciences with multimodal artificial intelligence and complex systems. His research focuses on neural decoding, brain-computer interfaces and computational models of perception. At NeuroVision, he leads the scientific vision, combining neuroscience-driven AI with predictive models of human attention." },
  { name:"Frantisek Hoza", role:"CTO & Head of Software Development", founder:true, image:sitePath("/assets/team-frantisek.webp"), bio:"Frantisek is a full-stack software engineer specialising in scalable architectures and high-performance systems. After starting his career in digital marketing, he moved into software engineering through a deep interest in data-driven behaviour and the algorithms that shape decision-making. At NeuroVision, he leads platform architecture and core product development." },
  { name:"Tereza Molnar", role:"Chief Product Officer", founder:true, image:sitePath("/assets/team-tereza.webp"), bio:"Tereza combines economics, business development and design to translate complex technology into useful products. With more than nine years of experience across branding, marketing and creative direction, she focuses on bridging science and real-world application. She previously worked as an art director at a technology startup and later pursued a master’s degree in Innovation Management." },
  { name:"Aleksandra Krolikowska", role:"Sales & Project Manager", image:sitePath("/assets/team-aleksandra.webp"), bio:"Aleksandra connects client needs with clear project delivery, supporting commercial relationships and helping NeuroVision initiatives move from opportunity to execution." },
  { name:"Jakub Lenovsky", role:"Head of CRM & Sales", image:sitePath("/assets/team-jakub.webp"), bio:"Jakub leads customer relationships and sales development, supporting the adoption of NeuroVision’s data-driven marketing tools." },
  { name:"Maria Kostrzewa", role:"Science & Business Development", image:sitePath("/assets/team-maria.webp"), bio:"Maria supports research initiatives and helps translate NeuroVision’s scientific insights into practical business applications." },
  { name:"Milosz Panasik", role:"Sales & Sustainability", image:sitePath("/assets/team-milosz.webp"), bio:"Milosz supports sales and integrates sustainability perspectives into NeuroVision’s strategy and partnerships." },
  { name:"Hana Vyroubalova", role:"Business Developer & Sales Specialist", image:sitePath("/assets/team-hana.png"), bio:"Hana builds trust before she builds pipelines. Her background spans consultative sales, customer success, content and social entrepreneurship—giving every client relationship a sharp commercial focus and a distinctly human tone." },
  { name:"Denisa Kubova", role:"UX & Visual Design Specialist", image:sitePath("/assets/team-denisa.png"), bio:"Denisa gives ideas a visual system people want to keep. Her practice crosses UX, branding, illustration, print and packaging, with an unusually precise eye for the details that make an experience feel considered rather than decorated." },
  { name:"Eva Paracuellos", role:"Software Developer", initials:"EP", bio:"Eva contributes to the product experience and engineering systems that turn NeuroVision’s research workflows into dependable software." },
  { name:"Fadil Abdussemee", role:"Software Developer", initials:"FA", bio:"Fadil develops and strengthens the software behind NeuroVision’s analysis, workflow and product-delivery capabilities." },
  { name:"Apurv Nishit", role:"Software Developer", initials:"AN", bio:"Apurv supports platform development across the technical stack, helping NeuroVision deliver fast, scalable creative intelligence." },
];

export default function About(){
  return <><Header/><main id="main-content">
    <section className="page-hero about-hero"><div className="container about-hero-grid"><div><p className="kicker">About NeuroVision</p><h1>Better creative starts with a better understanding of people.</h1><p className="lead">NeuroVision brings attention science, AI audience feedback and creative tools together, so teams can test and improve designs before launch.</p></div><div className="about-manifesto"><span>We connect</span><b>What people notice</b><b>What people understand</b><b>What creative teams do next</b></div></div></section>
    <WhyDifferent id="why-neurovision-is-different" />
    <section className="inner-section why-started"><div className="container story-layout"><div className="story-intro"><p className="kicker">Why we started</p><h2>More creative was being produced.<br />Too little was truly understood.</h2><p className="story-lead">Creating more options became easier. Choosing between them did not.</p></div><div className="story-body"><p>Creative teams can now move at extraordinary speed. But the most important questions often remain unanswered until after launch: What captured attention? What did the audience take away? Which direction deserves investment?</p><p>The answers are often scattered across heatmaps, surveys and campaign reports. Meanwhile, AI creates more options without making the choice any easier.</p><p>We built NeuroVision to bring these questions into one workflow: predict attention, explore how the message may be understood, then create and test a new version.</p><div className="origin-principle"><span>Our principle</span><b>Make evidence usable while creative decisions are still adjustable.</b></div></div><div className="story-path" aria-label="NeuroVision decision workflow"><span><i>01</i><b>See</b><small>Predict attention</small></span><span><i>02</i><b>Understand</b><small>Explore perception</small></span><span><i>03</i><b>Improve</b><small>Redesign with evidence</small></span></div></div></section>
    <section className="section team"><div className="container"><div className="section-head"><div><p className="kicker light">The team behind NeuroVision</p><h2>Meet the people building the future of design intelligence.</h2></div><p>NeuroVision brings together neuroscience, product engineering, design, operations and market development across Europe and Asia.</p></div><div className="team-grid detailed-team">{team.map(member=><article className={"founder" in member&&member.founder?"founder-card":""} key={member.name}>{member.image?<img src={member.image} alt={member.name}/>:<div className="team-placeholder" aria-label={`${member.name} profile image not yet available`}><span>{member.initials}</span><i/><i/></div>}<div className="team-copy">{"founder" in member&&member.founder&&<span className="founder-label">Co-founder</span>}<p className="team-role">{member.role}</p><h3>{member.name}</h3><p className="team-bio">{member.bio}</p></div></article>)}</div></div></section>
    <section className="section values"><div className="container"><div className="section-head"><div><p className="kicker">What connects us</p><h2>Different skills. One shared purpose.</h2></div><p>We combine neuroscience, design and software to make creative testing useful in everyday work.</p></div><div className="discipline-cloud"><span>Neuroscience</span><span>UX &amp; visual design</span><span>Artificial intelligence</span><span>Neural networks</span><span>Software engineering</span><span>Innovation management</span><span>Behavioural science</span><span>Commercial strategy</span></div><div className="value-grid"><div><span>Evidence</span><h3>Science with intellectual honesty</h3><p>We work with probabilities, limitations and context—then make them clear enough to guide a real creative decision.</p></div><div><span>Translation</span><h3>Make complex tools easy to use</h3><p>We turn complex models into clear guidance that designers and marketers can use.</p></div><div><span>Amplification</span><h3>Human judgement, upgraded</h3><p>We combine computational power with taste, responsibility and creative direction. The machine expands the view; people make the call.</p></div></div></div></section>
    <section className="final-cta"><div className="container"><p className="kicker light">Build with us</p><h2>Bring clearer evidence to your creative work.</h2><p>We welcome product feedback, research conversations, pilot projects and partnerships.</p><div className="actions center"><a className="btn white" href="mailto:info@neurovision-ai.com?subject=NeuroVision%20conversation">Start a conversation ↗</a><a className="btn ghost" href="https://app.neurovision-ai.com/register">Try the platform</a></div></div></section>
  </main><Footer/></>;
}
