import type { Metadata } from "next";
import { Footer, Header } from "../site-shell";
import { sitePath } from "../site-path";
import { WhyDifferent } from "../why-different";

export const metadata: Metadata = { title:"About", description:"Meet the multidisciplinary team building NeuroVision." };

const team = [
  { name:"Patrik Molnar", role:"CEO & Chief Scientist", founder:true, image:sitePath("/assets/team-patrik.webp"), bio:"Patrik is a computational neuroscience researcher exploring how neuroscience and biophysics can inspire the next generation of intelligent systems. He currently works at the Chinese Academy of Sciences with multimodal artificial intelligence and complex systems. His research focuses on neural decoding, brain-computer interfaces and computational models of perception. At NeuroVision, he leads the scientific vision, combining neuroscience-driven AI with predictive models of human attention." },
  { name:"Frantisek Hoza", role:"CTO & Head of Software Development", founder:true, image:sitePath("/assets/team-frantisek.webp"), bio:"Frantisek is a full-stack software engineer specialising in scalable architectures and high-performance systems. After starting his career in digital marketing, he moved into software engineering through a deep interest in data-driven behaviour and the algorithms that shape decision-making. At NeuroVision, he leads platform architecture and core product development." },
  { name:"Tereza Molnar", role:"Chief Product Officer", founder:true, image:sitePath("/assets/team-tereza.webp"), bio:"Tereza combines economics, business development and design to translate complex technology into useful products. With more than nine years of experience across branding, marketing and creative direction, she focuses on bridging science and real-world application. She previously worked as an art director at a technology startup and later pursued a master’s degree in Innovation Management." },
  { name:"Aleksandra Krolikowska", role:"Sales & Project Manager", image:sitePath("/assets/team-aleksandra.webp"), bio:"Aleksandra connects client needs with clear project delivery, supporting commercial relationships and helping NeuroVision initiatives move from opportunity to execution." },
  { name:"Jakub Lenovsky", role:"Head of CRM & Sales", image:sitePath("/assets/team-jakub.webp"), bio:"Jakub leads customer relationships and sales development, supporting the adoption of NeuroVision’s data-driven marketing tools." },
  { name:"Maria Kostrzewa", role:"Science & Business Development", image:sitePath("/assets/team-maria.webp"), bio:"Maria supports research initiatives and helps translate NeuroVision’s scientific insights into practical business applications." },
  { name:"Milosz Panasik", role:"Sales & Sustainability", image:sitePath("/assets/team-milosz.webp"), bio:"Milosz supports sales and integrates sustainability perspectives into NeuroVision’s strategy and partnerships." },
  { name:"Hana Vyroubalova", role:"Business Developer & Sales Specialist", image:sitePath("/assets/team-hana.png"), bio:"Hana builds trust before she builds pipelines. Her background spans consultative sales, customer success, content and social entrepreneurship—giving every client relationship a sharp commercial focus and a distinctly human tone." },
  { name:"Denisa Kubova", role:"UX & Visual Design Specialist", image:sitePath("/assets/team-denisa.png"), bio:"Denisa gives ideas a visual system people want to keep. Her practice crosses UX, branding, illustration, print and packaging, with an unusually precise eye for the details that make an experience feel considered rather than decorated." },
  { name:"Eva Paracuellos", role:"Software Developer", initials:"EP", bio:"Eva contributes to the product experience and engineering systems that turn NeuroVision’s research workflows into dependable software." },
  { name:"Fadil Abdussemee", role:"Software Developer", initials:"FA", bio:"Fadil develops and strengthens the software behind NeuroVision’s analysis, workflow and product-delivery capabilities." },
  { name:"Apurv Nishit", role:"Software Developer", initials:"AN", bio:"Apurv supports platform development across the technical stack, helping NeuroVision deliver fast, scalable creative intelligence." },
];

export default function About(){
  return <><Header/><main id="main-content">
    <section className="page-hero about-hero"><div className="container about-hero-grid"><div><p className="kicker">About NeuroVision</p><h1>Better creative starts with understanding people.</h1><p className="lead">We bring attention science, AI audience feedback and creative tools together, so teams can test and improve designs before launch.</p></div></div></section>
    <WhyDifferent id="why-neurovision-is-different" />
    <section className="inner-section why-started"><div className="container story-layout"><div className="story-intro"><h2>More creative was being produced.<br />Too little was truly understood.</h2></div><div className="story-body"><p>Creating more options became easier. Choosing between them did not. Teams still needed to know what people would notice, what the message meant to them, and which version to develop.</p><p>We built NeuroVision to bring those questions into one place, while there is still time to change the design. Our models help teams test ideas; people bring the judgement and creative direction.</p></div></div></section>
    <section className="section team"><div className="container"><div className="section-head"><div><h2>Meet the team.</h2></div><p>Researchers, engineers and creative specialists working together across Europe and Asia.</p></div><div className="team-grid detailed-team">{team.map(member=><article className={"founder" in member&&member.founder?"founder-card":""} key={member.name}>{member.image?<img src={member.image} alt={member.name} loading="lazy"/>:<div className="team-placeholder" aria-label={`${member.name} profile image not yet available`}><span>{member.initials}</span><i/><i/></div>}<div className="team-copy"><h3>{member.name}</h3><p className="team-role">{member.role}{"founder" in member&&member.founder&&<> · Co-founder</>}</p><details className="team-details"><summary>About {member.name.split(" ")[0]}<span aria-hidden="true">+</span></summary><p className="team-bio">{member.bio}</p></details></div></article>)}</div></div></section>
    <section className="final-cta"><div className="container"><h2>Let’s work together.</h2><p>Talk to us about a project, a research question or a partnership.</p><div className="actions center"><a className="btn white" href="mailto:info@neurovision-ai.com?subject=NeuroVision%20conversation">Start a conversation ↗</a><a className="btn ghost" href="https://app.neurovision-ai.com/register">Try the platform</a></div></div></section>
  </main><Footer/></>;
}
