export const plans = [
  {
    name: "FREE",
    price: "€0",
    credits: "40 credits / month",
    description: "Explore before committing.",
    features: ["Predictive attention heatmaps", "AI creative critique", "Surveys up to 25 responses", "1 seat"],
    cta: "Start free",
  },
  {
    name: "STANDARD",
    price: "€25",
    credits: "200 credits / month",
    description: "For freelancers and solo marketers.",
    features: ["Everything in Free", "Surveys up to 50 responses", "1 seat"],
    cta: "Get started",
  },
  {
    name: "PRO",
    price: "€79",
    credits: "800 credits / month",
    description: "For small teams.",
    features: ["Everything in Standard", "Surveys with 100+ responses", "PDF report download", "2 seats"],
    cta: "Get started",
    featured: true,
  },
  {
    name: "PREMIUM",
    price: "€249",
    credits: "2,500 credits / month",
    description: "For agencies, e-commerce brands, and high-volume creative teams.",
    features: ["Everything in Pro", "Priority support", "5 seats"],
    cta: "Get started",
  },
];

export const agencyPackages = [
  {
    label: "Diagnose and improve",
    name: "Signal Review",
    description: "A focused scientific evaluation of one campaign direction, with practical improvements your team can use immediately.",
    price: "€690",
    features: [
      "Up to 3 static assets or 1 landing page",
      "NeuroVision heatmaps & design psychology",
      "What is seen, missed and misunderstood",
      "Agentic audience pulse for 1 target profile",
      "Prioritized GenAI recommendations",
      "2 generated optimization variants",
      "Up to 3 platform-ready resizes",
      "Annotated report + A/B comparison",
      "30-minute expert readout",
      "Human-led production redesign",
    ],
  },
  {
    label: "The complete diagnostic",
    name: "Performance Deep Dive",
    description: "Our strongest analysis package for teams deciding between concepts or preparing a campaign for meaningful media spend.",
    price: "€1,390",
    features: [
      "Up to 6 assets or 2 creative concepts",
      "Full NeuroVision analysis stack",
      "NeuroVision Digital Shelf snapshot",
      "Agentic survey across 3 audience profiles",
      "Semantic, cultural & geographic risk review",
      "A/B comparison across concepts",
      "3 generated optimization variants",
      "Up to 6 platform-ready resizes",
      "Executive report + 60-minute workshop",
      "One recommendation feedback round",
      "Human-led production redesign",
    ],
    featured: true,
  },
  {
    label: "Analysis, redesign, proof",
    name: "Creative Lab",
    description: "A full optimization sprint: diagnose the campaign, redesign its most important moments and test the improved directions again.",
    price: "€2,790",
    features: [
      "Up to 10 assets or 3 creative concepts",
      "Everything in Performance Deep Dive",
      "Full NeuroVision Digital Shelf benchmark",
      "2 expert-designed creative directions",
      "Brand, copy, hierarchy and UX redesign",
      "Re-test against the original creative",
      "Campaign-ready files and required resizes",
      "90-minute creative workshop",
    ],
  },
];

