import type { Metadata } from "next";
import { Footer, Header } from "../site-shell";

export const metadata: Metadata = { title:"Science & Validation", description:"How NeuroVision connects visual attention research, neural modelling, benchmarking and academic validation." };

const stages = [
  { tag:"Human signal", title:"Start with how people actually look.", copy:"Eye-tracking measures where attention moves across a visual stimulus. Gaze points and fixations create the empirical signal used to develop and evaluate predictive attention systems. NeuroVision builds on this established scientific tradition to estimate likely early-attention patterns without requiring new lab equipment for every creative.", fact:"Ground truth: measured gaze and fixation behaviour", art:"science-eye" },
  { tag:"Research data", title:"Learn across diverse visual environments.", copy:"Modern vision models learn from large collections of natural scenes, interfaces, advertising and other visual stimuli paired with human attention data. Training across varied material helps a model learn recurring relationships between contrast, faces, objects, text, composition and gaze.", fact:"Diverse stimuli · controlled human observation · independent test sets", art:"science-data" },
  { tag:"Model architecture", title:"Use the world’s leading computational vision research.", copy:"Our attention layer uses advanced deep neural modelling informed by leading work in computational saliency and visual neuroscience, including research traditions associated with MIT and the Tübingen vision-science community. Hierarchical neural representations are translated into spatial attention probabilities—not deterministic claims about an individual person.", fact:"Deep neural features → spatial probability → interpretable heatmap", art:"science-model" },
  { tag:"Benchmarking", title:"Test on images the model has not seen.", copy:"A credible model must generalise. Predictions are evaluated against held-out human eye-tracking data using established saliency metrics and visual inspection. We track performance across content types, examine failure cases and treat every score as a probabilistic decision aid.", fact:"Independent evaluation · error analysis · documented limitations", art:"science-check" },
];

export default function Science(){
  return <><Header/><main>
    <section className="page-hero science-hero"><div className="container page-hero-grid"><div><p className="kicker">Science &amp; validation</p><h1>From human gaze to useful creative evidence.</h1></div><p className="lead">A clear account of the data, models and validation logic behind NeuroVision—for people who want scientific depth without a research-paper obstacle course.</p></div></section>
    <section className="science-roadmap"><div className="container"><div className="science-roadmap-head"><p className="kicker light">The evidence pathway</p><h2>Measured behaviour in. Probabilistic guidance out.</h2><p>Our process separates what is established, what is modelled and what is still being validated.</p></div><div className="roadmap-line">{stages.map((stage,index)=><article key={stage.tag}><div className={`science-stage-art ${stage.art}`}><i/><i/><i/><b>{index+1}</b></div><div><span>{stage.tag}</span><h3>{stage.title}</h3><p>{stage.copy}</p><small>{stage.fact}</small></div></article>)}</div></div></section>
    <section className="section science-stack"><div className="container"><div className="section-head"><div><p className="kicker">More than one model</p><h2>Three scientific layers answer three different questions.</h2></div><p>Attention, interpretation and optimisation should not be collapsed into a single magical score. Each layer has a distinct job and evidence standard.</p></div><div className="science-layer-grid"><article><span>01 / Perception</span><h3>Predictive attention</h3><p>Estimates early visual hierarchy: what may attract gaze, what competes and what risks being missed.</p><b>Output</b><small>Heatmaps, attention clarity, product and brand visibility</small></article><article><span>02 / Meaning</span><h3>Agentic audience research</h3><p>Extends beyond the opening glance into structured semantic interpretation across defined audience profiles.</p><b>Output</b><small>Clarity, trust, relevance, themes and segment differences</small></article><article><span>03 / Action</span><h3>Evidence-led generation</h3><p>Turns diagnosed weaknesses into constrained creative alternatives, then returns each variant through the same evaluation loop.</p><b>Output</b><small>Traceable briefs, A/B comparisons and improved variants</small></article></div></div></section>
    <section className="section aarhus"><div className="container aarhus-grid"><div><p className="kicker light">Academic validation · Aarhus University</p><h2>Testing whether prediction and simulation resemble reality.</h2><p>We work with leading scientists at Aarhus University to evaluate how closely predictive attention and agentic survey research correspond with controlled human response—and how useful the combined workflow is in real creative decisions.</p><p>The collaboration also helps us identify additional data subsets that can strengthen model performance for the visual contexts where current systems are least certain.</p><div className="validation-questions"><span>Do predicted hotspots align with measured gaze?</span><span>Do agentic themes resemble independent human answers?</span><span>Do combined insights improve practical creative decisions?</span></div></div><aside><span>Research programme</span><h3>Prediction → comparison → refinement</h3><ol><li>Controlled visual stimuli</li><li>Human eye-tracking and survey response</li><li>Model predictions generated independently</li><li>Quantitative and qualitative comparison</li><li>Failure analysis and targeted data expansion</li></ol><p><strong>Please stay tuned.</strong> Outcomes and research communication will be shared here as the work progresses.</p></aside></div></section>
    <section className="science-caveat"><div className="container"><strong>What NeuroVision is—and is not.</strong><p>NeuroVision is a fast, scalable decision layer for screening and improving creative work. It does not replace every eye-tracking study, representative consumer study or expert judgement. Outputs are probabilities and structured evidence, not guarantees of behaviour or commercial performance.</p></div></section>
  </main><Footer/></>;
}
