import type { Metadata } from "next";
import Link from "next/link";
import { Footer, Header } from "../site-shell";
import { sitePath } from "../site-path";
import { CreativeVisual } from "../creative-visual";
import { creativeExamples } from "../creative-examples";

export const metadata: Metadata = {
  title: "Use Cases",
  description: "Explore how NeuroVision supports campaigns, websites, digital shelf, packaging and product decisions.",
};

const useCases = [
  { id:"01", label:"Campaigns & ads", title:"Choose your campaign creative before you spend.", copy:"Compare concepts, messages and generated variants while there is still time to change them. NeuroVision shows whether the product, headline, brand and call to action form the hierarchy you intended.", tasks:["Pre-flight a hero campaign","Compare paid-social variants","Check brand and CTA visibility","Build an evidence-backed creative review"], outputs:["Attention map","Audience interpretation","A/B recommendation"], art:"campaign-art" },
  { id:"02", label:"Websites & UX", title:"Make your page easier to understand.", copy:"Analyse full-page captures or key interface states to see what attracts the opening view, what is visually buried and where the page asks users to work too hard.", tasks:["Review landing-page hierarchy","Check CTA discoverability","Compare hero and navigation options","Trace attention across a long page"], outputs:["First-view hierarchy","Clarity risks","Prioritised UX changes"], art:"website-art" },
  { id:"03", label:"Digital shelf", title:"Help your product stand out in a crowded listing.", copy:"Benchmark product listings against the surrounding shelf. See which product gains presence, whether critical details survive thumbnail scale and how brand assets perform against competitors.", tasks:["Compare search-result thumbnails","Benchmark product presence","Audit titles, badges and pack visibility","Screen new listing creatives"], outputs:["Shelf ranking","Product visibility","Competitive benchmark"], art:"shelf-art" },
  { id:"04", label:"Packaging & product", title:"Test what the pack communicates before production.", copy:"Evaluate shelf presence, information order and brand recognition across early packaging concepts. AI audience profiles help you explore whether the message feels clear, credible and relevant.", tasks:["Compare pack architecture","Check claim readability","Evaluate range consistency","Test recognition at realistic scale"], outputs:["Pack attention","Message clarity","Variant comparison"], art:"packaging-art" },
];

function UseCaseArt({ type }: { type: string }) {
  if (type === "campaign-art") return <figure className="use-case-art supplied-use-case"><CreativeVisual asset={creativeExamples[0].recreated} /><figcaption>Supplied Adidas creative example</figcaption></figure>;
  if (type === "website-art") return <figure className="use-case-art supplied-website"><img src={sitePath("/assets/examples/tonys-website.webp")} alt="Supplied Tony’s Chocolonely website screenshot" loading="lazy" /><figcaption>Website screenshot supplied for illustration</figcaption></figure>;
  if (type === "shelf-art") return <div className="use-case-art shelf-art amazon-shelf"><header><b>shop</b><span className="static-search">sparkling water</span><span>Search</span></header><section>{["LIME","PURE","BERRY","CITRUS"].map((name,index)=><div className={index===1?"winner":""} key={name}><i/><strong>{name}</strong><small>12-pack · 4.6 ★</small>{index===1&&<><em>SELECTED</em><u/></>}</div>)}</section><aside>Illustrative shelf layout</aside></div>;
  if (type === "packaging-art") return <div className="use-case-art packaging-art soda-pack"><span><small>NV / SPARK</small><b>VOLT</b><em>YUZU + LIME</em><u>330 ml</u></span><i/><div><b>Brand</b><span>Check visibility</span><b>Flavour</b><span>Check readability</span></div></div>;
  return <div className="use-case-art generation-art supplied-generation"><div><small>Original</small><img src={sitePath(creativeExamples[1].original.src)} alt={creativeExamples[1].original.alt} loading="lazy" /></div><b aria-hidden="true">→</b><div><small>Recreated</small><img src={sitePath(creativeExamples[1].recreated.src)} alt={creativeExamples[1].recreated.alt} loading="lazy" /></div><p>Illustrative redesign. Measured results are not available.</p></div>;
}

export default function UseCases() {
  return (
    <><Header /><main id="main-content">
      <section className="page-hero use-cases-hero"><div className="container page-hero-grid"><div><p className="kicker">Made for visual decisions</p><h1>Test your creative wherever people see it.</h1></div><p className="lead">Use NeuroVision to check ads, websites, product listings and packaging before they reach your audience.</p></div></section>
      <section className="section decision-strip decision-after-hero"><div className="container"><p className="kicker light">Three useful questions</p><h2>One workflow. Different creative questions.</h2><div className="decision-grid"><div><span className="decision-icon">◉</span><b>Does it get seen?</b><p>Predict early attention and visual hierarchy.</p></div><div><span className="decision-icon">◫</span><b>Does it get understood?</b><p>Explore meaning, clarity, trust and relevance.</p></div><div><span className="decision-icon">✦</span><b>What could improve?</b><p>Create and compare a new version.</p></div></div><Link className="btn white" href="/how-it-works">See how it works →</Link></div></section>
      <section className="use-case-list"><div className="container">{useCases.map((item,index)=><article className={`use-case-row ${index%2?"reverse":""}`} key={item.id}><UseCaseArt type={item.art}/><div className="use-case-copy"><p className="case-number">{item.id} / {item.label}</p><h2>{item.title}</h2><p>{item.copy}</p><div className="use-case-details"><div><strong>Use NeuroVision to</strong><ul>{item.tasks.map(task=><li key={task}>{task}</li>)}</ul></div><div><strong>Typical outputs</strong><ul>{item.outputs.map(output=><li key={output}>{output}</li>)}</ul></div></div></div></article>)}</div></section>
      <section className="section extend-workflow"><div className="container"><div className="section-head"><div><p className="kicker">After the visual test</p><h2>Understand the response. Then improve the design.</h2></div><p>Add audience feedback when you need to understand the message, then use the findings to guide a new design.</p></div><div className="extension-flow">
        <article className="extension-card survey-extension"><div className="extension-top"><span className="extension-icon">◫</span><p>Optional audience feedback</p></div><h3>Run an AI audience survey</h3><p>Ask AI-simulated profiles consistent questions about the message, trust and relevance. Use their answers to identify what needs further testing.</p><div className="survey-proof"><blockquote>What is the main message? What is unclear? Would you want to know more?</blockquote><small>Example survey questions</small></div><ul><li>Choose audience profiles and sample size</li><li>Compare themes and segment differences</li><li>Add semantic insight to attention evidence</li></ul></article>
        <div className="flow-connector" aria-hidden="true"><span>Attention + survey findings</span><b>→</b></div>
        <article className="extension-card generation-extension"><div className="extension-top"><span className="extension-icon">✦</span><p>Creative improvement</p></div><h3>Create the next version</h3><p>Start with a suggested redesign, or set your own prompt, brand rules and format. Compare each new version with the original.</p><UseCaseArt type="generation-art"/><div className="generation-paths"><span><b>Quick optimise</b><small>One-click evidence-led redesign</small></span><span><b>Advanced GenAI</b><small>Prompt, constrain, resize and iterate</small></span></div><ul><li>Generate on-brand alternatives</li><li>Re-test every variant against the original</li><li>Export the version you choose</li></ul></article>
      </div></div></section>
      <section className="final-cta"><div className="container"><p className="kicker light">Bring your own visual</p><h2>Start with the creative decision in front of you.</h2><p>Analyse one asset, compare a campaign system or run the complete loop across your next launch.</p><div className="actions center"><a className="btn white" href="https://app.neurovision-ai.com/register">Try NeuroVision free ↗</a><a className="btn ghost" href="mailto:info@neurovision-ai.com?subject=NeuroVision%20use%20case">Discuss your use case</a></div></div></section>
    </main><Footer /></>
  );
}
