import type { Metadata } from "next";
import Link from "next/link";
import { Footer, Header } from "../site-shell";

export const metadata: Metadata = {
  title: "Use Cases",
  description: "Explore how NeuroVision supports campaigns, websites, digital shelf, packaging and product decisions.",
};

const useCases = [
  { id:"01", label:"Campaigns & ads", title:"Choose the creative worth backing before media spend.", copy:"Compare concepts, messages and generated variants while there is still time to change them. NeuroVision shows whether the product, headline, brand and call to action form the hierarchy you intended.", tasks:["Pre-flight a hero campaign","Compare paid-social variants","Check brand and CTA visibility","Build an evidence-backed creative review"], outputs:["Attention map","Audience interpretation","A/B recommendation"], art:"campaign-art" },
  { id:"02", label:"Websites & UX", title:"Find conversion friction before it becomes analytics.", copy:"Analyse full-page captures or key interface states to see what attracts the opening view, what is visually buried and where the page asks users to work too hard.", tasks:["Review landing-page hierarchy","Check CTA discoverability","Compare hero and navigation options","Trace attention across a long page"], outputs:["First-view hierarchy","Clarity risks","Prioritised UX changes"], art:"website-art" },
  { id:"03", label:"Digital shelf", title:"Win attention in the most competitive few centimetres online.", copy:"Benchmark product listings against the surrounding shelf. See which product gains presence, whether critical details survive thumbnail scale and how brand assets perform against competitors.", tasks:["Compare search-result thumbnails","Benchmark product presence","Audit titles, badges and pack visibility","Screen new listing creatives"], outputs:["Shelf ranking","Product visibility","Competitive benchmark"], art:"shelf-art" },
  { id:"04", label:"Packaging & product", title:"Test what the pack communicates before production.", copy:"Evaluate shelf presence, information order and brand recognition across early packaging concepts. Agentic audiences add a first-pass view of clarity, trust, relevance and likely misunderstanding.", tasks:["Compare pack architecture","Check claim readability","Evaluate range consistency","Test recognition at realistic scale"], outputs:["Pack attention","Message clarity","Variant comparison"], art:"packaging-art" },
];

function UseCaseArt({ type }: { type: string }) {
  if (type === "campaign-art") return <div className="use-case-art campaign-art"><span>MOVE<br />DIFFERENT.</span><span>BUILT<br />TO MOVE.</span><b>A/B</b></div>;
  if (type === "website-art") return <div className="use-case-art website-art"><div><i /><strong>Make every first view count.</strong><em /><button>Start now</button></div><u /><u /></div>;
  if (type === "shelf-art") return <div className="use-case-art shelf-art amazon-shelf"><header><b>shop</b><input aria-label="Product search" value="sparkling water" readOnly/><span>Search</span></header><section>{["LIME","PURE","BERRY","CITRUS"].map((name,index)=><div className={index===1?"winner":""} key={name}><i/><strong>{name}</strong><small>12-pack · 4.6 ★</small>{index===1&&<><em>ANALYSED</em><u/></>}</div>)}</section><aside>Predicted shelf attention <b>87</b></aside></div>;
  if (type === "packaging-art") return <div className="use-case-art packaging-art soda-pack"><span><small>NV / SPARK</small><b>VOLT</b><em>YUZU + LIME</em><u>330 ml</u></span><i/><div><b>Brand</b><span>81%</span><b>Flavour</b><span>68%</span></div></div>;
  return <div className="use-case-art generation-art remake-art"><div><small>Before · original</small><span><b>MOVE<br/>DIFFERENT.</b></span></div><b>→</b><div className="remade"><small>After · AI-remade</small><span><b>BUILT<br/>TO MOVE.</b></span></div><em>Hierarchy +18%</em><u>Headline clarified · product enlarged · CTA restored</u></div>;
}

export default function UseCases() {
  return (
    <><Header /><main>
      <section className="page-hero use-cases-hero"><div className="container page-hero-grid"><div><p className="kicker">Made for visual decisions</p><h1>One intelligence layer across your creative stack.</h1></div><p className="lead">Run the same science-backed evaluation wherever customers meet your brand—from the first campaign concept to the final product listing.</p></div></section>
      <section className="section decision-strip decision-after-hero"><div className="container"><p className="kicker light">A repeatable decision layer</p><h2>One workflow. Different creative questions.</h2><div className="decision-grid"><div><span className="decision-icon">◉</span><b>Does it get seen?</b><p>Predict early attention and visual hierarchy.</p></div><div><span className="decision-icon">◫</span><b>Does it get understood?</b><p>Explore meaning, clarity, trust and relevance.</p></div><div><span className="decision-icon">✦</span><b>Can it work harder?</b><p>Generate and compare evidence-led variations.</p></div></div><Link className="btn white" href="/how-it-works">See how the workflow works →</Link></div></section>
      <section className="use-case-list"><div className="container">{useCases.map((item,index)=><article className={`use-case-row ${index%2?"reverse":""}`} key={item.id}><UseCaseArt type={item.art}/><div className="use-case-copy"><p className="case-number">{item.id} / {item.label}</p><h2>{item.title}</h2><p>{item.copy}</p><div className="use-case-details"><div><strong>Use NeuroVision to</strong><ul>{item.tasks.map(task=><li key={task}>{task}</li>)}</ul></div><div><strong>Typical outputs</strong><ul>{item.outputs.map(output=><li key={output}>{output}</li>)}</ul></div></div></div></article>)}</div></section>
      <section className="section extend-workflow"><div className="container"><div className="section-head"><div><p className="kicker">After the visual test</p><h2>Understand the response. Then improve the design.</h2></div><p>Whichever visual format you begin with, NeuroVision can extend the attention result into structured audience feedback—and turn both evidence layers into a stronger creative direction.</p></div><div className="extension-flow">
        <article className="extension-card survey-extension"><div className="extension-top"><span className="extension-icon">◫</span><p>Optional perception layer</p></div><h3>Run an agentic survey</h3><p>Move beyond the opening glance. Ask a defined audience how they perceive the message, brand, trust, relevance and emotional meaning of the visual.</p><div className="survey-proof"><span><small>Message clarity</small><b><i style={{width:"82%"}}/></b></span><span><small>Brand trust</small><b><i style={{width:"74%"}}/></b></span><blockquote>“The product feels premium, but the main benefit could be clearer.”</blockquote></div><ul><li>Choose audience profiles and sample size</li><li>Compare themes and segment differences</li><li>Add semantic insight to attention evidence</li></ul></article>
        <div className="flow-connector" aria-hidden="true"><span>Attention + survey findings</span><b>→</b></div>
        <article className="extension-card generation-extension"><div className="extension-top"><span className="extension-icon">✦</span><p>Evidence-led action layer</p></div><h3>Redesign by click—or take full control</h3><p>Use a one-click optimisation for speed, or open the detailed GenAI workflow to adjust the prompt, brand constraints, channel format and creative direction.</p><UseCaseArt type="generation-art"/><div className="generation-paths"><span><b>Quick optimise</b><small>One-click evidence-led redesign</small></span><span><b>Advanced GenAI</b><small>Prompt, constrain, resize and iterate</small></span></div><ul><li>Generate on-brand alternatives</li><li>Re-test every variant against the original</li><li>Export the evidence-backed winner</li></ul></article>
      </div></div></section>
      <section className="final-cta"><div className="container"><p className="kicker light">Bring your own visual</p><h2>Start with the creative decision in front of you.</h2><p>Analyse one asset, compare a campaign system or run the complete loop across your next launch.</p><div className="actions center"><a className="btn white" href="http://app.neurovision-ai.com/register">Try NeuroVision free ↗</a><a className="btn ghost" href="mailto:info@neurovision-ai.com?subject=NeuroVision%20use%20case">Discuss your use case</a></div></div></section>
    </main><Footer /></>
  );
}
